$(document).ready(function () {
    $('#Gen').click(function (e) { 
        $('h1').text('Genesis');
        $('#p1').text('In the beginning, there was a Creator. The supreme being gave life to Gods who would be responsible for creating worlds and Gods in charge of destroying the decrepit ones.These are known as deities and demons respectively.Instead of living with the deities in the physical world, Elyos was created to house the ferocious demons. When necessary, the demons would traverse through the Dimensional Portals to cause destruction.');
        $('#Loreimg').attr('src', '../image/image7.jpg');
        $('#p2').text(' he gods descended on the continent of Archimedia located in the primitive world of Aernas. Kakaodeityillust Ernasis the goddess of war and bravery, Lisnar the goddess of mercy and spirit, and Amenias the goddess of wisdom and harmony led to the creation of the world.The world was named after Ernasis, the representative god who had first arrived. It was inhabited by the humans, elves, and dwarves and the goddess selected those with bravery and creativity to help them continue the creation of the world. The gods quickly civilized primitive humans so that they could be spread throughout the world and deliver their will. Ernasis gifted them with bravery, Lisnar gifted them with holiness and Amenias gifted them with wisdom. With these gifts in hand, the humans bravely expanded their territory, learned to use magic, and used the wisdom to develop machinery.Combining their powers, the gods and humans created a civilization at the center of Archimedia and called it Kounat.  Many of the gods fell in love with the humans and the children conceived were born with distinguishable abilities unlike those that were born of just human parents. As the numbers of these children increased, they became known as the Celestials and with the gods, they accelerated the development of magic in Kounat. With Kounat at the core, the magic civilization spread to the whole region of Archimedia.');
        $('#Loreimg2').attr('src', '../image/image8.png');
        $('#p3').text('The dwarves and the elves that inhabited the northern and southern regions of Kounat became influenced by the Celestials and through the exchange of information, accepted the advanced civilization. From the exchange, the elves were able to use more powerful magic and the dwarves obtained information to advance their mechanical engineering. Out of sight of other goddesses, the Malevolent Horde grew and threatened to destroy everything good in Aernas. On a trip to the East, the goddess of life and purity Agnesia found innocents suffering and came face to face with the terrible magical creature made of pure evil. Agnesia used all her powers to seal the creature within her own body and save the world but the consequence of using that forbidden magic drained almost all of her divine powers, leading her to the brink of death. Should Agnesia die, the evil in her body would be released. On her last legs and spending the last spark of her divine power, Agnesia cast a spell of eternal resurrection. Through the ages, Agnesia would be doomed to continue being reborn to keep the seal intact.');
    });
});

$('#Chaos').click(function (e) { 
    $('h1').text('Chaos');
    $('#p1').text('Brotherly nations, Kanavan kingdom, and Serdin kingdom declared the first year of Kingdom Calendar at the same time.Eckhart Sieghart, the ancestor of the Sieghart family, rejected the top general position bestowed upon him by King Kanavan and left the palace to become the leader of the Ruby Knights. As the leader, he journeyed across the lands to find the areas inhabited by monsters. For generations, the Kanavan kingdom produced outstanding swordsmen and the Serdin kingdom produced outstanding mages. The two kingdoms progressed greatly based on their virtues. Presumably, General Esnar Din Kanavan would then succeed King Kanavan as the ruler.');
    $('#Loreimg').attr('src', '../image/image9.jpg');
    $('#p2').text('ven after several hundreds of years after the establishment of the kingdoms, Baldinar had survived as an astral form due to the effects of the Soul Stone that he had created. Though he had lost all his powers, his ambitions remained and he wandered the world to find clues to powers that could revive him. Baldinar continued to survive in his astral form, by taking demonic essence from the demons and monsters all over Aernas and soon arrived in Xenia. The Six Gods of Xenia During the Great Explosion of Kounat, the Soul Stone had shattered and six pieces of the stone had landed in Xenia. The native guardians that had existed in Xenia, each took a piece of the Soul Stone and believing it to be the essence of the gods. With the stones, they governed Xenia as the six gods. Once Baldinar realized that the essence that each god held was a piece of the Soul Stone, he snuck deep into the land and began to spread the demonic essence he had acquired. The demonic essence dispersed into the land, turning the animals and living beings into monsters to infect the gods with darkness. Due to the evil energy that had been spread by Baldinar, numerous creatures in Xenia evolved into monsters and with it, the gods started to lose their sanity. Taking advantage of the confusion, Baldinar approached Ashtaroth, the guardian of Fortress of Ascension stole his soul and made him his puppet. Finally acquiring a useful body, Baldinar was able to secretly move about Xenia without the other gods realizing the situation and put Xenia in a further state of chaos. With his powers, he strengthened the monsters wandering the world and alienated the humans to create war.');
    $('#Loreimg2').attr('src', '../image/image10.png');
    $('#p3').text('The 35th successor of the Sieghart Family, Ercnard Sieghart was born on April 30 in the Kanavan kingdom. As a talented swordsman, Ercnard joined the Sieghart family Ruby Knights, but also spent a short time as part of the Royal Knights and was officially recorded in history books of the royal family. At some point, Ercnard also became a Sword Master.Following the source of monsters, Ercnard Sieghart made his way to Archimedia. Once arrived, he was attacked by monsters of incomparable strength than those that he had dealt with in Bermesiah. Gravely wounded, he was saved by the squad of Highlanders who had survived since the time of the ancient Kounat. Reborn as a Highlander with an immortal body, Sieghart was taught how to fight using his newfound powers. However, by his own mistake, his saviors were found and all killed by Ashtaroth. Being the sole survivor, Sieghart swore vengeance against Ashtaroth and began to travel the world to track him down.');
});

$('#Age').click(function (e) { 
    $('h1').text('Age of Heroes');
    $('#p1').text('Long ago after he became a Highlander, Ercnard Sieghart abandoned his name. However, the swordsmen of Kanavan that had watched him fight instinctively thought of the famous Sieghart family and began to call him Sieghart.During the war between the deities of Xenia, Lilith who was a Starlet, the highest of Oracles, was kidnapped by the Ascendant God Thanatos and the position has been vacant ever since. In her youth, Sister Maggie had to fill the position herself.Since then she has been training and encouraging young sisters in hopes of finding the right girl to fill the position of a Starlet.Later in Ellia, Lass had his body stolen by Kazeaze and plants her soul inside him to use him as a puppet.');
    $('#Loreimg').attr('src', '../image/image11.png');
    $('#p2').text('When Rin turned 15, the village of Gaon was wiped out by a massive attack of demonic creatures. All the inhabitants fought bravely, but in the end, Rin was the only one to escape with her life. Behind that attack were the Evil Priests, servants of the ancient evil that sought to break free.The traumatized Rin was taken by fury. It made her feel the evil growing inside her, trying to break free from the seal. Having come in contact with her dark side for the first time, Rin thought that she needed help to contain the evil within.Armed with her sacred fan, Rin decided to ask for help from the people of the great city whose stories she heard since she was a child. The last Asura sensed the gathering of malignant forces and summoned the most distinguished warriors to bestow his divine teachings. However, the warriors had neither the strength of the body nor the strength of mind to absorb the knowledge. Defeated by the Ascendant God, the Asura announced his final holy edict and commanded that once a great warrior was found, he shall inherit his title.Heeding the late Asuras call, Jin took on the rigorous test of improving his mind and fighting skills. Upon receiving Chamma and the divine teachings, Jin became the new Asura. Victor, Jins master and former leader of the Silver Knights, had been training to become a Rama. However, his ill intentions failed him to achieve enlightenment. Not being able to accept failure, Victor hid the Vajra, a set of powerful weapons used by the Rama, in his fortress.At some point, Thanatos came upon Victors mind and influenced his betrayal to the Silver Knights. Given newfound strength by the Ascendant God, Victor started his militia, the Black Knights, to wreak havoc and corrupt Silver Land with dark energy.');
    $('#Loreimg2').attr('src', '../image/image12.png');
    $('#p3').text('A nameless boy found the badly wounded Asin Tairin and saved his life. Tairin returned the favor by training the young boy with martial arts.When Tairin told him stories of his former student, Jin, the boy became determined to get stronger.One day, another battle ensued as monsters invaded the area, leaving Tairin in a fatal condition. Two weeks later, Tairin has died. Deranged, the young boy swore to become stronger than anyone including Jin and took his masters name as his.Ronan emerged from the ranks to lead the Aegis Knights and rallied against the invasion and repeated attacks that followed from Kazeaze.As Bermesiah continues to suffer from the war, the elves created a special bow made of Innadrils scales passed on from their ancestors with the hope of returning peace to the continent. Only the elite archers were allowed to use the bow.These archers are known as Arch Rangers. Serre discovered that they can convert their mana to cast powerful spells if they form contracts with spirits. However, the spirits are particular about whom they work with and join hands only with mages of exceptional power and character.These mages are known as Warlocks. Despite the allied forces of Elven Corps, Violet Mage, and Silver Cross, they remained vastly outnumbered.To compensate, the Silver Cross has been training more Dark Assassins to effectively counter monsters.Realizing that they cannot fend monsters with transformation alone, Chief Moru Pisu endowed the Druids with the power of Mother Nature.Only a special group of Sentinels succeeded to bear the life force upon their souls and has been honored with the title of Viken. Before the formation of Grand Chase, Elesis competed against the son of Depas Farenwhite, Gerard, for the leadership of the Ruby Knights.In the end, Elesis won the contest for leadership and was appointed the leader of the Ruby Knights. After Elesis left for Serdin to join the Grand Chase, Gerard leads the Ruby Knights in her stead and supports her in her mission.Before the formation of Grand Chase, Lire is a member of the Elven Corps and was dispatched to join the Grand Chase.The childhood friend of Lire, Myrielle Ariaden, had always wanted to leave Eryuell Island but when the chance went to Lire, Myrielle told her to see the rest of the world for her.Before the formation of Grand Chase, Arme is a member of the Violet Mage guild.Hoping to encounter Kazeaze and study her magic, Arme was off to form a team after Serre received the letter from Queen Serdins couriers');
});